/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */

#ifndef _DT_BINDINGS_MEMORY_MEDIATEK_MT6735_M4U_H_
#define _DT_BINDINGS_MEMORY_MEDIATEK_MT6735_M4U_H_

#include <dt-bindings/memory/mtk-memory-port.h>

#define M4U_PORT_DISP_OVL0		MTK_M4U_ID(0, 0)
#define M4U_PORT_DISP_RDMA0		MTK_M4U_ID(0, 1)
#define M4U_PORT_DISP_WDMA0		MTK_M4U_ID(0, 2)
#define M4U_PORT_DISP_RDMA1		MTK_M4U_ID(0, 3)
#define M4U_PORT_MDP_RDMA		MTK_M4U_ID(0, 4)
#define M4U_PORT_MDP_WDMA		MTK_M4U_ID(0, 5)
#define M4U_PORT_MDP_WROT		MTK_M4U_ID(0, 6)

#define M4U_PORT_HW_VDEC_MC_EXT		MTK_M4U_ID(1, 0)
#define M4U_PORT_HW_VDEC_PP_EXT		MTK_M4U_ID(1, 1)
#define M4U_PORT_HW_VDEC_AVC_MV_EXT	MTK_M4U_ID(1, 2)
#define M4U_PORT_HW_VDEC_PRED_RD_EXT	MTK_M4U_ID(1, 3)
#define M4U_PORT_HW_VDEC_PRED_WR_EXT	MTK_M4U_ID(1, 4)
#define M4U_PORT_HW_VDEC_VLD_EXT	MTK_M4U_ID(1, 5)
#define M4U_PORT_HW_VDEC_PPWRAP_EXT	MTK_M4U_ID(1, 6)

#define M4U_PORT_IMGO			MTK_M4U_ID(2, 0)
#define M4U_PORT_RRZO			MTK_M4U_ID(2, 1)
#define M4U_PORT_AAO			MTK_M4U_ID(2, 2)
#define M4U_PORT_LCSO			MTK_M4U_ID(2, 3)
#define M4U_PORT_ESFKO			MTK_M4U_ID(2, 4)
#define M4U_PORT_IMGO_S			MTK_M4U_ID(2, 5)
#define M4U_PORT_LSCI			MTK_M4U_ID(2, 6)
#define M4U_PORT_LSCI_D			MTK_M4U_ID(2, 7)
#define M4U_PORT_BPCI			MTK_M4U_ID(2, 8)
#define M4U_PORT_BPCI_D			MTK_M4U_ID(2, 9)
#define M4U_PORT_UFDI			MTK_M4U_ID(2, 10)
#define M4U_PORT_IMGI			MTK_M4U_ID(2, 11)
#define M4U_PORT_IMG2O			MTK_M4U_ID(2, 12)
#define M4U_PORT_IMG3O			MTK_M4U_ID(2, 13)
#define M4U_PORT_VIPI			MTK_M4U_ID(2, 14)
#define M4U_PORT_VIP2I			MTK_M4U_ID(2, 15)
#define M4U_PORT_VIP3I			MTK_M4U_ID(2, 16)
#define M4U_PORT_LCEI			MTK_M4U_ID(2, 17)
#define M4U_PORT_RB			MTK_M4U_ID(2, 18)
#define M4U_PORT_RP			MTK_M4U_ID(2, 19)
#define M4U_PORT_WR			MTK_M4U_ID(2, 20)

#define M4U_PORT_VENC_RCPU		MTK_M4U_ID(3, 0)
#define M4U_PORT_VENC_REC		MTK_M4U_ID(3, 1)
#define M4U_PORT_VENC_BSDMA		MTK_M4U_ID(3, 2)
#define M4U_PORT_VENC_SV_COMV		MTK_M4U_ID(3, 3)
#define M4U_PORT_VENC_RD_COMV		MTK_M4U_ID(3, 4)
#define M4U_PORT_JPGENC_RDMA		MTK_M4U_ID(3, 5)
#define M4U_PORT_JPGENC_BSDMA		MTK_M4U_ID(3, 6)
#define M4U_PORT_JPGDEC_WDMA		MTK_M4U_ID(3, 7)
#define M4U_PORT_JPGDEC_BSDMA		MTK_M4U_ID(3, 8)
#define M4U_PORT_VENC_CUR_LUMA		MTK_M4U_ID(3, 9)
#define M4U_PORT_VENC_CUR_CHROMA	MTK_M4U_ID(3, 10)
#define M4U_PORT_VENC_REF_LUMA		MTK_M4U_ID(3, 11)
#define M4U_PORT_VENC_REF_CHROMA	MTK_M4U_ID(3, 12)

#endif
